services:
  # The Redis Instance
  - name: redis-cache
    type: redis
    plan: free

  # The Backend Web Service
  - name: backend-server
    type: web
    plan: free
    runtime: node
    repo: https://github.com/your-github-username/your-repo-name
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: DATABASE_URL
        sync: false # Add this manually from PlanetScale
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: RESEND_API_KEY
        sync: false # Add this manually
      - key: GEMINI_API_KEY
        sync: false # Add this manually
  
  # The Frontend Static Site
  - name: frontend-client
    type: static
    plan: free
    repo: https://github.com/pramodbamne/AI-task-manager
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishDir: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html